import { Colour, ColourFamilyData } from './types';

export const HERO_COLOURS: Colour[] = [
  {
    name: 'Linen White',
    hex: '#F5F0E8',
    family: 'Neutrals',
    mood: 'A clean, warm white that opens up any room without feeling clinical. Pairs beautifully with natural wood and aged brass.',
    advice: 'Ideal for south and east-facing rooms. Use with a warm white ceiling to avoid a sterile feel.',
    complementaryAccent: '#C4956B',
  },
  {
    name: 'Morning Fog',
    hex: '#D4D1CB',
    family: 'Neutrals',
    mood: 'Soft grey-beige that shifts between warm and cool depending on the light. A reliable base for any interior scheme.',
    advice: 'Works in any aspect. Pair with off-white woodwork rather than bright white for a cohesive result.',
    complementaryAccent: '#8B9E7E',
  },
  {
    name: 'Stone Ground',
    hex: '#C8BFA9',
    family: 'Neutrals',
    mood: 'Warm putty with genuine depth. Not quite beige, not quite grey. The backbone of a considered interior.',
    advice: 'Excellent in north-facing rooms where it brings warmth. Pair with linen textiles and dark oak.',
    complementaryAccent: '#C4956B',
  },
  {
    name: 'Sage Leaf',
    hex: '#8B9E7E',
    family: 'Greens',
    mood: 'A grounding green that works beautifully with natural light and linen textures.',
    advice: 'Works well in north-facing rooms. Pairs naturally with brass hardware and off-white woodwork.',
    complementaryAccent: '#C4956B',
  },
  {
    name: 'Nordic Blue',
    hex: '#7B9DB7',
    family: 'Blues',
    mood: 'Calm, considered, and quietly confident. The blue of Scandinavian interiors done properly.',
    advice: 'Best in rooms with natural daylight. Pairs with white linen, pale timber, and matte black fixtures.',
    complementaryAccent: '#C8BFA9',
  },
  {
    name: 'Ink Wash',
    hex: '#4A5568',
    family: 'Statement',
    mood: 'A sophisticated blue-grey with enough depth to anchor a room without overwhelming it.',
    advice: 'Use on feature walls or in studies. Pair with warm brass lighting for balance.',
    complementaryAccent: '#D4A9A0',
  },
  {
    name: 'Warm Clay',
    hex: '#C4956B',
    family: 'Earth',
    mood: 'Earthy, grounding terracotta warmth. Brings the outside in and works with every skin tone in the room.',
    advice: 'Superb in west-facing rooms for evening warmth. Pairs with deep greens and aged leather.',
    complementaryAccent: '#8B9E7E',
  },
  {
    name: 'Blush Plaster',
    hex: '#D4A9A0',
    family: 'Statement',
    mood: 'Soft pink with real plaster depth. Mature, not saccharine. The blush that works for grown-ups.',
    advice: 'Flattering in bedrooms and dining rooms. Pair with warm whites and unlacquered brass.',
    complementaryAccent: '#8B9E7E',
  },
  {
    name: 'Midnight Teal',
    hex: '#2D5F5D',
    family: 'Statement',
    mood: 'Deep, enveloping teal that makes a room feel like an intention, not an accident.',
    advice: 'Bold on all four walls in small spaces. Pair with natural rattan and warm lighting.',
    complementaryAccent: '#C4956B',
  },
  {
    name: 'Charcoal Linen',
    hex: '#3D3B38',
    family: 'Statement',
    mood: 'Near-black with warmth. Dramatic without being cold. The dark room done right.',
    advice: 'All four walls including ceiling for a cocooning effect. Pair with warm-toned art and lighting.',
    complementaryAccent: '#C4956B',
  },
];

export const COLOUR_FAMILIES: ColourFamilyData[] = [
  {
    name: 'Neutrals',
    description: 'Warm whites, greys, and stones that work as the backbone of any scheme.',
    colours: [
      {
        name: 'Linen White',
        hex: '#F5F0E8',
        family: 'Neutrals',
        mood: 'Warm, clean, never clinical.',
        advice: 'Ideal for south-facing rooms. Use with warm-white woodwork.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Morning Fog',
        hex: '#D4D1CB',
        family: 'Neutrals',
        mood: 'Shifts between warm and cool with the light.',
        advice: 'Works in any aspect. Pair with off-white woodwork.',
        complementaryAccent: '#8B9E7E',
      },
      {
        name: 'Stone Ground',
        hex: '#C8BFA9',
        family: 'Neutrals',
        mood: 'Warm putty with genuine depth.',
        advice: 'Excellent in north-facing rooms. Pair with dark oak.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Pale Chalk',
        hex: '#EDE8E0',
        family: 'Neutrals',
        mood: 'The palest warm white, almost no colour at all.',
        advice: 'Perfect for ceilings and woodwork alongside any wall colour.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Aged Plaster',
        hex: '#D8D0C4',
        family: 'Neutrals',
        mood: 'The colour of a Georgian wall after two centuries of good taste.',
        advice: 'Period properties in particular. Beautiful with original cornicing.',
        complementaryAccent: '#8B9E7E',
      },
      {
        name: 'Parchment',
        hex: '#E8E0D0',
        family: 'Neutrals',
        mood: 'Warm cream with a papery quality.',
        advice: 'Hallways and landings. Works with almost anything.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Warm Ash',
        hex: '#B8B0A4',
        family: 'Neutrals',
        mood: 'Medium grey with warmth. Sits between stone and slate.',
        advice: 'Great in contemporary interiors. Pair with white oak and concrete.',
        complementaryAccent: '#7B9DB7',
      },
      {
        name: 'Silver Birch',
        hex: '#C4BEBC',
        family: 'Neutrals',
        mood: 'Cool-leaning grey with a touch of lilac in certain light.',
        advice: 'North-facing rooms where a cool, calm feel is desired.',
        complementaryAccent: '#D4A9A0',
      },
    ],
  },
  {
    name: 'Earth',
    description: 'Clays, terracottas, and ochres grounded in the landscape.',
    colours: [
      {
        name: 'Warm Clay',
        hex: '#C4956B',
        family: 'Earth',
        mood: 'Earthy warmth. Brings the outside in.',
        advice: 'West-facing rooms for evening warmth. Pairs with deep greens.',
        complementaryAccent: '#8B9E7E',
      },
      {
        name: 'Terracotta Dust',
        hex: '#C47B5A',
        family: 'Earth',
        mood: 'Earthy red-orange. Mediterranean warmth without the cliche.',
        advice: 'Kitchens and dining rooms. Excellent with olive green accents.',
        complementaryAccent: '#8B9E7E',
      },
      {
        name: 'Harvest Ochre',
        hex: '#C9A84C',
        family: 'Earth',
        mood: 'Warm yellow-gold. Autumn fields in paint form.',
        advice: 'Use sparingly. Accent walls and alcoves. Pairs with deep navy.',
        complementaryAccent: '#4A5568',
      },
      {
        name: 'Raw Umber',
        hex: '#A07850',
        family: 'Earth',
        mood: 'Deep brown-orange. Serious, grounded, considered.',
        advice: 'Studies and libraries. Pair with bottle green and aged leather.',
        complementaryAccent: '#2D5F5D',
      },
      {
        name: 'Sandstone',
        hex: '#D4BC94',
        family: 'Earth',
        mood: 'Pale sand with warmth. Desert light through a window.',
        advice: 'Great in kitchens and bathrooms. Clean and warm simultaneously.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Fired Earth',
        hex: '#B06040',
        family: 'Earth',
        mood: 'Deep terracotta. The colour of a kiln.',
        advice: 'Feature walls only. Powerful in small doses.',
        complementaryAccent: '#2D5F5D',
      },
      {
        name: 'Brick Dust',
        hex: '#C0785C',
        family: 'Earth',
        mood: 'Warm red-brown. Victorian brick in softer form.',
        advice: 'Period properties. Naturally sympathetic to exposed brickwork.',
        complementaryAccent: '#8B9E7E',
      },
    ],
  },
  {
    name: 'Greens',
    description: 'Sage, olive, and forest greens for rooms that feel alive.',
    colours: [
      {
        name: 'Sage Leaf',
        hex: '#8B9E7E',
        family: 'Greens',
        mood: 'Grounding and calm. Works with natural light.',
        advice: 'Works well in north-facing rooms. Pairs with brass hardware.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Olive Press',
        hex: '#7A8A60',
        family: 'Greens',
        mood: 'Yellow-green. Mediterranean olive groves at dusk.',
        advice: 'Kitchens and dining rooms. Pair with terracotta and warm wood.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Forest Floor',
        hex: '#4A5E40',
        family: 'Greens',
        mood: 'Deep, mossy green. Serious and enveloping.',
        advice: 'All four walls for a dramatic effect. Pair with natural linen.',
        complementaryAccent: '#C8BFA9',
      },
      {
        name: 'Lichen',
        hex: '#A4B090',
        family: 'Greens',
        mood: 'Pale grey-green. The colour of stone walls after rain.',
        advice: 'Bathrooms and bedrooms. Naturally calming.',
        complementaryAccent: '#D4A9A0',
      },
      {
        name: 'Juniper',
        hex: '#5C7260',
        family: 'Greens',
        mood: 'Blue-green with depth. Between sage and forest.',
        advice: 'Pairs well with warm whites and natural timber.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Fern',
        hex: '#6B8060',
        family: 'Greens',
        mood: 'Fresh mid-green. Spring morning in a pot.',
        advice: 'Garden rooms and orangeries. Excellent with terracotta tiles.',
        complementaryAccent: '#C4956B',
      },
    ],
  },
  {
    name: 'Blues',
    description: 'Duck egg to navy. Every blue worth considering.',
    colours: [
      {
        name: 'Nordic Blue',
        hex: '#7B9DB7',
        family: 'Blues',
        mood: 'Calm and confident. Scandinavian restraint.',
        advice: 'Best in rooms with natural daylight. Pairs with pale timber.',
        complementaryAccent: '#C8BFA9',
      },
      {
        name: 'Duck Egg',
        hex: '#8EB4B4',
        family: 'Blues',
        mood: 'Soft blue-green. Coastal without being obvious about it.',
        advice: 'Bathrooms and bedrooms. Naturally restful.',
        complementaryAccent: '#D4A9A0',
      },
      {
        name: 'Powder Blue',
        hex: '#A8C0D0',
        family: 'Blues',
        mood: 'Pale and airy. The blue of a clear winter morning.',
        advice: 'Children\'s rooms and bedrooms. Light and uplifting.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Steel Blue',
        hex: '#5C7A94',
        family: 'Blues',
        mood: 'Mid blue with grey undertones. Industrial meets refined.',
        advice: 'Studies and home offices. Focused and calming.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Ink Wash',
        hex: '#4A5568',
        family: 'Blues',
        mood: 'Blue-grey depth. Anchors a room.',
        advice: 'Feature walls. Pair with warm brass lighting.',
        complementaryAccent: '#D4A9A0',
      },
      {
        name: 'Harbour',
        hex: '#3D6080',
        family: 'Blues',
        mood: 'Deep nautical blue. Confident and serious.',
        advice: 'Dining rooms and hallways. Pairs with white woodwork.',
        complementaryAccent: '#C8BFA9',
      },
    ],
  },
  {
    name: 'Statement',
    description: 'Deep teal, charcoal, and blush for rooms that commit.',
    colours: [
      {
        name: 'Midnight Teal',
        hex: '#2D5F5D',
        family: 'Statement',
        mood: 'Deep and enveloping. A room that means business.',
        advice: 'Bold on all four walls in small spaces. Warm lighting essential.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Charcoal Linen',
        hex: '#3D3B38',
        family: 'Statement',
        mood: 'Near-black with warmth. The dark room done right.',
        advice: 'All four walls and ceiling for cocooning effect.',
        complementaryAccent: '#C4956B',
      },
      {
        name: 'Blush Plaster',
        hex: '#D4A9A0',
        family: 'Statement',
        mood: 'Mature blush. Not saccharine. The pink that works.',
        advice: 'Bedrooms and dining rooms. Pairs with warm whites.',
        complementaryAccent: '#8B9E7E',
      },
      {
        name: 'Deep Aubergine',
        hex: '#4A2D4A',
        family: 'Statement',
        mood: 'Rich purple-brown. Theatrical but grounded.',
        advice: 'Studies and feature walls. Pair with warm gold lighting.',
        complementaryAccent: '#C8BFA9',
      },
      {
        name: 'Oxide Red',
        hex: '#8C3A30',
        family: 'Statement',
        mood: 'Deep brick red. Historic and commanding.',
        advice: 'Period dining rooms. Spectacular with candlelight.',
        complementaryAccent: '#C8BFA9',
      },
      {
        name: 'Petrol',
        hex: '#2C4A50',
        family: 'Statement',
        mood: 'Dark teal-blue. The colour of refinement.',
        advice: 'Bathrooms and bedrooms. Pairs with aged brass.',
        complementaryAccent: '#C4956B',
      },
    ],
  },
];

export const ALL_COLOURS: Colour[] = COLOUR_FAMILIES.flatMap(f => f.colours);

export const getColourByName = (name: string): Colour | undefined =>
  ALL_COLOURS.find(c => c.name === name);

export const getColourByHex = (hex: string): Colour | undefined =>
  ALL_COLOURS.find(c => c.hex.toLowerCase() === hex.toLowerCase());
