import { Service, Project, Testimonial, ProcessStep, BeforeAfterCard, RoomTemplate } from './types';

export const SERVICES: Service[] = [
  {
    id: 'interior-painting',
    title: 'Interior Painting',
    tagline: 'Walls, ceilings, woodwork. Prep that you will not see but will feel in the finish.',
    description: 'Every interior job starts the same way: surfaces assessed, imperfections filled, and everything masked before a brush or roller touches a wall. We use Crown Trade and Dulux Heritage on most domestic projects, with Farrow & Ball and Little Greene where clients specify. New plaster gets a mist coat. Stained ceilings get shellac-based primer. The right primer for the surface, every time. Then two full coats minimum, cut-in by hand, with roller technique chosen to match the finish required.',
    includes: [
      'Full surface preparation and filling',
      'Mist coat on new plaster',
      'Shellac primer on stained or nicotine ceilings',
      'Two full coats of client-specified paint',
      'Cut-in edges by hand',
      'All masking, dust sheets, and protection included',
      'Leftover paint labelled and left with you',
    ],
    startingFrom: 'From £350 per room (walls and ceiling)',
    timescale: '1 to 2 days per room',
    image: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=1200&q=80',
    imageAlt: 'Freshly painted interior room with smooth finish',
  },
  {
    id: 'exterior-painting',
    title: 'Exterior Painting',
    tagline: 'Front doors to full facades. Weather-matched paint systems for the East Midlands.',
    description: 'Exterior work in the East Midlands demands paint systems built for damp autumns and frozen winters. We use masonry paints rated for the climate, with appropriate primers for bare render, pebbledash, and brick. Front doors get Farrow & Ball exterior eggshell or Zinsser oil-based primer plus Dulux Trade for durability. We do not rush exterior work. Surfaces get cleaned, any blown render repaired, and cracks filled with flexible exterior filler before we pick up a brush.',
    includes: [
      'Surface assessment and preparation',
      'Flexible exterior filler on cracks',
      'Weather-appropriate masonry paint system',
      'Front door and woodwork in oil-based eggshell',
      'Soffits, fascias, and guttering painted if required',
      'Full masking and garden protection',
    ],
    startingFrom: 'From £800 (front elevation only)',
    timescale: '1 to 3 days depending on size',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
    imageAlt: 'Freshly painted exterior front door in bold colour',
  },
  {
    id: 'wallpapering',
    title: 'Wallpapering',
    tagline: 'Pattern matching, feature walls, heritage papers. Hung with zero bubbles.',
    description: 'Wallpapering is the trade skill that separates decorators from painters who also hang paper. Pattern matching on large-repeat papers requires planning before the first strip goes up. We have hung Cole & Son, Zoffany, Sanderson, and most of the major heritage paper houses. Feature walls in Edwardian semis in Sherwood or full-room wallpaper in new-builds in Gamston, the approach is always the same: plumb lines set, walls sized if needed, and every seam joined invisibly.',
    includes: [
      'Wall preparation and sizing',
      'Pattern matching planned before work begins',
      'All major paper brands accepted',
      'Feature walls or full-room hanging',
      'Seams checked and pressed on completion',
      'Removal of old wallpaper if required (quoted separately)',
    ],
    startingFrom: 'From £200 per wall (supply and hang)',
    timescale: 'Half a day to 1 day per wall depending on pattern',
    image: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=1200&q=80',
    imageAlt: 'Elegant wallpapered feature wall in living room',
  },
  {
    id: 'colour-consultation',
    title: 'Colour Consultation',
    tagline: 'Not sure what works? We bring the swatches, the experience, and the confidence so you do not have to guess.',
    description: 'Most decorating mistakes happen before any paint is mixed. A colour that looks right on a small chip in a bright showroom can completely change character on four walls of a north-facing bedroom. Our consultation service is a proper visit: we assess the light, the floor, the fixtures, the furniture, and then we work through options together using full A4 drawdown samples and our own fan decks from Farrow & Ball, Little Greene, and Dulux Heritage. You leave with three confident colour choices and a written scheme. The £75 fee comes off any subsequent job.',
    includes: [
      'In-home visit of up to 2 hours',
      'Up to 3 rooms covered',
      'Full A4 sample drawdowns in your space',
      'Farrow & Ball, Little Greene, and Dulux Heritage fan decks',
      'Written colour scheme with brand and code references',
      'Advice on finishes: matt, eggshell, satin',
      'Fee deducted from project if booked',
    ],
    startingFrom: '£75 for up to 3 rooms',
    timescale: '2 hour visit, scheme delivered within 48 hours',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80',
    imageAlt: 'Interior designer reviewing paint colour swatches',
  },
  {
    id: 'period-restoration',
    title: 'Period Property Restoration',
    tagline: 'Cornicing, dado rails, lime wash. Sympathetic work that respects the original character.',
    description: 'Victorian terraces on Alfreton Road. Edwardian semis in Sherwood. Georgian townhouses in the Park Estate. Nottingham has exceptional period housing stock and it deserves decorators who understand it. Original cornicing gets cleaned, not caulked into oblivion. Lime-washed walls get lime-compatible finishes, not modern emulsions that trap moisture. Sash windows get the correct oil-based primer sequence. We work with the fabric of old buildings rather than against it, and we will tell you when something needs a specialist beyond decorating.',
    includes: [
      'Cornice cleaning and careful preparation',
      'Lime wash and lime-compatible paint systems',
      'Oil-based primer sequence for original joinery',
      'Matching heritage paint colours to existing schemes',
      'Advice on historically appropriate finishes',
      'Liaison with conservation officers where required',
    ],
    startingFrom: 'Quoted per project',
    timescale: 'Varies by scope',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80',
    imageAlt: 'Victorian interior with ornate cornicing and period details',
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'west-bridgford-hall',
    title: 'Full Interior Scheme',
    location: 'West Bridgford',
    category: 'Interior',
    rooms: 6,
    colours: ['Nordic Blue', 'Linen White', 'Stone Ground'],
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80',
    imageAlt: 'Elegant living room in Nordic Blue',
  },
  {
    id: 'beeston-victorian',
    title: 'Victorian Terrace Restoration',
    location: 'Beeston',
    category: 'Period',
    rooms: 4,
    colours: ['Sage Leaf', 'Linen White', 'Warm Clay'],
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    imageAlt: 'Period living room with original features',
  },
  {
    id: 'sherwood-feature',
    title: 'Feature Wall and Joinery',
    location: 'Sherwood',
    category: 'Interior',
    rooms: 2,
    colours: ['Midnight Teal', 'Charcoal Linen'],
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    imageAlt: 'Dark teal feature wall in contemporary bedroom',
  },
  {
    id: 'mapperley-exterior',
    title: 'Full Exterior and Front Door',
    location: 'Mapperley',
    category: 'Exterior',
    colours: ['Charcoal Linen', 'Linen White'],
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
    imageAlt: 'Freshly painted exterior with bold front door',
  },
  {
    id: 'wollaton-wallpaper',
    title: 'Heritage Wallpaper Installation',
    location: 'Wollaton',
    category: 'Wallpaper',
    rooms: 3,
    colours: ['Stone Ground', 'Blush Plaster'],
    image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&q=80',
    imageAlt: 'Elegant wallpapered dining room',
  },
  {
    id: 'arnold-full-house',
    title: 'Full House Redecoration',
    location: 'Arnold',
    category: 'Interior',
    rooms: 7,
    colours: ['Morning Fog', 'Warm Clay', 'Sage Leaf'],
    image: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800&q=80',
    imageAlt: 'Open plan living space with neutral palette',
  },
  {
    id: 'park-estate-period',
    title: 'Georgian Townhouse Restoration',
    location: 'The Park, NG7',
    category: 'Period',
    rooms: 5,
    colours: ['Aged Plaster', 'Linen White', 'Harvest Ochre'],
    image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80',
    imageAlt: 'Georgian interior with restored period features',
  },
  {
    id: 'gamston-newbuild',
    title: 'New Build Full Interior',
    location: 'Gamston',
    category: 'Interior',
    rooms: 8,
    colours: ['Linen White', 'Nordic Blue', 'Blush Plaster'],
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    imageAlt: 'Contemporary new build interior with clean finish',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: 'They convinced us to try Nordic Blue in the hallway. We were nervous but it completely transformed the space. The light bounces off it in a way we never expected.',
    name: 'Sarah T.',
    location: 'West Bridgford',
    projectType: 'Full interior',
    accentColour: '#7B9DB7',
  },
  {
    quote: 'The prep work was incredible. Every crack filled, every edge perfect. You can run your hand along the walls and feel nothing but smooth paint. Worth every penny.',
    name: 'James K.',
    location: 'Beeston',
    projectType: 'Interior painting',
    accentColour: '#8B9E7E',
  },
  {
    quote: 'Our Victorian terrace has original cornicing and they treated it like it deserved. Beautiful careful work. Not a single bead of caulk where it should not be.',
    name: 'Priya R.',
    location: 'Sherwood',
    projectType: 'Period restoration',
    accentColour: '#C4956B',
  },
  {
    quote: 'Quoted on Tuesday, started Thursday, finished Monday. Exactly what they said it would cost. Absolutely no surprises. Genuinely rare in any trade.',
    name: 'Dan M.',
    location: 'Mapperley',
    projectType: 'Exterior and interior',
    accentColour: '#2D5F5D',
  },
  {
    quote: 'The colour consultation alone was worth it. They talked us out of the colour we thought we wanted and into Blush Plaster, which is now our favourite room in the house.',
    name: 'Hannah & Chris L.',
    location: 'Wollaton',
    projectType: 'Colour consultation',
    accentColour: '#D4A9A0',
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: 1,
    title: 'Consultation',
    description: 'We visit, assess surfaces, discuss colour, and leave you with a clear written quote. No hourly rates, no guessing. A fixed price for a defined scope.',
  },
  {
    number: 2,
    title: 'Preparation',
    description: 'Filling, sanding, masking, dust sheets. The work nobody photographs but everyone benefits from. This is where the quality of the finish is actually determined.',
  },
  {
    number: 3,
    title: 'Priming',
    description: 'The right primer for the surface. Bare plaster, new wood, stained walls. Each surface gets specific treatment. We do not skip this step.',
  },
  {
    number: 4,
    title: 'Application',
    description: 'Two full coats minimum. Cut-in edges by hand. Roller technique matched to the finish. No rushing. No cutting corners at the end of the day.',
  },
  {
    number: 5,
    title: 'Walkthrough',
    description: 'We inspect together. Any touch-ups done on the spot. Leftover paint labelled and left with you. Your home back, but better.',
  },
];

export const BEFORE_AFTER_CARDS: BeforeAfterCard[] = [
  {
    id: 'beeston-living',
    label: 'Full interior',
    location: 'Beeston, NG9',
    beforeImage: 'https://images.unsplash.com/photo-1598928636135-d146006ff4be?w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80',
    wipeDirection: 'tl-br',
  },
  {
    id: 'sherwood-hallway',
    label: 'Hallway and stairs',
    location: 'Sherwood, NG5',
    beforeImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800&q=80',
    wipeDirection: 'tr-bl',
  },
  {
    id: 'west-bridgford-bedroom',
    label: 'Master bedroom',
    location: 'West Bridgford, NG2',
    beforeImage: 'https://images.unsplash.com/photo-1522444195799-478538b28823?w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    wipeDirection: 'tl-br',
  },
  {
    id: 'wollaton-exterior',
    label: 'Exterior repaint',
    location: 'Wollaton, NG8',
    beforeImage: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
    wipeDirection: 'tr-bl',
  },
];

export const ROOM_TEMPLATES: RoomTemplate[] = [
  {
    id: 'living-room',
    label: 'Living Room',
    zones: [
      { id: 'main-wall', label: 'Main Wall', defaultColour: '#F5F0E8' },
      { id: 'feature-wall', label: 'Feature Wall', defaultColour: '#D4D1CB' },
      { id: 'ceiling', label: 'Ceiling', defaultColour: '#F5F0E8' },
      { id: 'trim', label: 'Skirting & Trim', defaultColour: '#FFFFFF' },
    ],
  },
  {
    id: 'bedroom',
    label: 'Bedroom',
    zones: [
      { id: 'walls', label: 'Walls', defaultColour: '#F5F0E8' },
      { id: 'ceiling', label: 'Ceiling', defaultColour: '#F5F0E8' },
      { id: 'wardrobe', label: 'Wardrobe Doors', defaultColour: '#FFFFFF' },
    ],
  },
  {
    id: 'kitchen',
    label: 'Kitchen',
    zones: [
      { id: 'walls', label: 'Walls', defaultColour: '#F5F0E8' },
      { id: 'cabinets', label: 'Cabinet Fronts', defaultColour: '#FFFFFF' },
      { id: 'ceiling', label: 'Ceiling', defaultColour: '#F5F0E8' },
    ],
  },
];

export const COVERAGE_AREAS = [
  'Nottingham',
  'West Bridgford',
  'Beeston',
  'Sherwood',
  'Mapperley',
  'Wollaton',
  'Arnold',
  'Carlton',
  'Long Eaton',
  'Hucknall',
  'Ruddington',
];
